include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_local_variable: ignore
    prefer_is_empty: ignore
    use_build_context_synchronously: ignore
    prefer_const_constructors: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_null_comparison: ignore
    deprecated_member_use: ignore
