name: flutter_geolocalizacion
description: Mi Ruta de Escape - app de rutas con OpenStreetMap y OSRM.
publish_to: "none"
version: 0.0.1+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  http: ^1.2.0
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.0.0
  flutter_polyline_points: ^2.0.0 # Para decodificar la geometría de OSRM/Google Maps

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/taxi.svg


